services:
  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      #- /var/log:/var/log
    command:
      - --api.dashboard=true
      - --log.level=INFO
      #- --log.filepath=/var/log/traefik.log
      - --accesslog=true
      #- --accesslog.filepath=/var/log/traefik-access.log
      - --providers.docker.network=traefik
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.email=rdppanahi@gmail.com
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`traefiks.panmal.ir`)
      - traefik.http.routers.mydashboard.service=api@internal
      - traefik.http.routers.mydashboard.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=admin:$$apr1$$lAr0hVtP$$NscpziwjrwWDY.fGHR0kv/
  whoami:
    image: traefik/whoami:v1.10
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.mywhoami.rule=Host(`webs.panmal.ir`)
      - traefik.http.routers.mywhoami.middlewares=mywhoami-auth
      - traefik.http.routers.mywhoami.service=mywhoami
      - traefik.http.middlewares.mywhoami-auth.basicauth.users=admin:$$apr1$$lAr0hVtP$$NscpziwjrwWDY.fGHR0kv/
      - traefik.http.services.mywhoami.loadbalancer.server.port=80
      - traefik.http.routers.mywhoami-unsecured.rule=Host(`webs.panmal.ir`) && PathPrefix(`/unsecured`)
      - traefik.http.routers.mywhoami-unsecured.service=mywhoami-unsecured
      - traefik.http.services.mywhoami-unsecured.loadbalancer.server.port=80
  nginx_srv:
    image: nginx
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`mail.panmal.ir`)
      - traefik.http.routers.nginx.service=mynginx
      - traefik.http.services.mynginx.loadbalancer.server.port=80
        #- traefik.http.routers.nginx.tls=true
        #- "traefik.http.routers.nginx.entrypoints=websecure"
        #- "traefik.http.routers.nginx.tls.certresolver=myresolver"
networks:
  traefik:
    external: true
volumes:
  letsencrypt:
    name: letsencrypt
